# _____________________________________
# Configuration instruction is here
# https://github.com/Banbeucmas/Oregen3/blob/master/README.md
# Please click if you use the plugin the first time or updating
# For the sake of using it PLEASE
# I will give you tacos if you do it :3
# -------------------------------------
# DO NOT TOUCH THIS

version: 1.3.0
prefix: "&f[&6OreGen&e3&f]"

mode:
  waterBlock: true
  lavaBlock: false
  waterLava: true

blocks:
- FENCE
- ACACIA_FENCE
- BIRCH_FENCE
- DARK_OAK_FENCE
- IRON_FENCE

disabledWorlds:
- world

enableDependency: true
randomFallback: false
defaultGenerator: default

generators:
  default:
    fallback: COBBLESTONE
    random:
      COBBLESTONE: 30.0
      GOLD_BLOCK: 20.0
      IRON_BLOCK: 15.0
      LAPIS_BLOCK: 2.0
  vip:
    fallback: COBBLESTONE
    permission: "test.vip"
    priority: 2
    level: 10
    random:
      COBBLESTONE: 30.0
      GOLD_BLOCK: 20.0
      IRON_BLOCK: 15.0
      LAPIS_BLOCK: 2.0
      COAL_BLOCK: 5.0
      REDSTONE_BLOCK: 10.0
  mvp:
    fallback: DIAMOND_ORE
    priority: 3
    level: 10
    random:
      COBBLESTONE: 30.0
      GOLD_BLOCK: 20.0
      IRON_BLOCK: 15.0
      LAPIS_BLOCK: 2.0
      COAL_BLOCK: 5.0
      REDSTONE_BLOCK: 10.0
      DIAMOND_BLOCK: 10.0
      EMERALD_BLOCK: 8.0

messages:
  gui:
    title: "&eChances"
    block:
      displayName: "&6%name%"
      lore:
      - "&6Chances: &e%chance%&6%"